name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./library_backend
          ruby-version: ruby-3.4.1
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        working-directory: ./library_backend
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./library_backend
          ruby-version: ruby-3.4.1
          bundler-cache: true

      - name: Lint code for consistent style
        working-directory: ./library_backend
        run: bin/rubocop -f github
